In [19]:
import sys
import os
sys.path.append(os.path.abspath("..")) # Moves up to the Project Root

In [20]:
from pulsekit import PulseKit
import numpy as np
import pandas as pd

### Initialize pipe

In [21]:
# init
pipe = PulseKit(data_loc="test_data")
print(pipe.sessions)

['3_2', '1', '2_2', '4', '3', '2', '5']

### segment beats

In [22]:
pipe.segment()
rp1_beats = pd.read_csv("test_data/1/segmented_beats.csv")
rp1_beats.head()

   cycle_id  beat_start  beat_end
0         0         716      1446
1         1        1446      2163
2         2        2163      2899
3         3        2899      3656
4         4        3656      4441

In [23]:
pipe.process_signal(["PPG_Finger"])

In [24]:
rp1_finger = pd.read_csv("test_data/1/PPG_Finger_processed.csv")
rp1_finger.head()

,cycle_id,beat_start,beat_end,quality_check_passed,peak,foot,foot_next,a,b,c,d,e,f,z,q,g
0,0,716,1446,True,1032.0,808.0,1385.0,948.0,1009.0,1077.0,1125.0,1214.0,1261.0,892.0,793.0,1299.0
1,1,1446,2163,True,1756.0,1657.0,2177.0,1684.0,1744.0,1812.0,1909.0,1961.0,2018.0,1637.0,1606.0,2129.0
2,2,2163,2899,False,2329.0,2177.0,2379.0,2376.0,1977.0,2018.0,2129.0,2216.0,2258.0,2330.0,2258.0,2330.0
3,3,2899,3656,True,3350.0,2924.0,3865.0,3123.0,3178.0,3237.0,3285.0,3353.0,3406.0,3076.0,3037.0,3456.0
4,4,3656,4441,True,3937.0,3865.0,4329.0,3870.0,3927.0,3983.0,4011.0,4048.0,4099.0,3821.0,3778.0,4190.0

In [25]:
pipe.process_signal(["PPG_Wrist", "Digital_Stethoscope", "Earbud_Lef"])

ValueError: Signal Earbud_Lef not recognized. Possible signals are: ['PPG_Finger', 'PPG_Ear', 'PPG_Wrist', 'Earbud_Left', 'Earbud_Right', 'ECG', 'Digital_Stethoscope', 'AccX', 'AccY', 'AccZ']

In [13]:
rp1_Stethoscope = pd.read_csv("test_data/1/Digital_Stethoscope_processed.csv")
rp1_Stethoscope.head()

   cycle_id  beat_start  beat_end  quality_check_passed    s1
0         0         716      1446                  True   770
1         1        1446      2163                  True  1488
2         2        2163      2899                  True  2189
3         3        2899      3656                  True  2922
4         4        3656      4441                  True  3689

In [11]:
rp1_Wrist = pd.read_csv("test_data/1/PPG_Wrist_processed.csv")
rp1_Wrist.head()

,cycle_id,beat_start,beat_end,quality_check_passed,peak,foot,foot_next,a,b,c,d,e,f,z,q,g
0,0,716,1446,False,1401.0,1364.0,1630.0,1627.0,1164.0,1188.0,1254.0,1295.0,1331.0,1592.0,1542.0,1365.0
1,1,1446,2163,False,1759.0,1630.0,1974.0,1638.0,1689.0,1721.0,1761.0,1812.0,1853.0,1592.0,1542.0,1891.0
2,2,2163,2899,False,2586.0,2183.0,2962.0,2353.0,2412.0,2455.0,2496.0,2541.0,2586.0,2307.0,2266.0,2626.0
3,3,2899,3656,False,3929.0,2962.0,4150.0,3106.0,3157.0,3240.0,3292.0,3345.0,3387.0,3020.0,2972.0,3420.0
4,4,3656,4441,True,3929.0,3699.0,4150.0,3867.0,3920.0,3995.0,4038.0,4078.0,4106.0,3823.0,3800.0,4142.0

### Old Fiducials Comparison

In [17]:
fiducials = pd.read_csv("fiducials/fiducials_with_tests.csv")
rp1_fiducials = fiducials[fiducials["participant_tag"] == "rp1"]
rp1_fiducials.head()

,participant_tag,cycle,ecg_peak,ecg_peak_next,sbp,dbp,pcg_s1,ppg_finger_peak,ppg_finger_foot,ppg_finger_foot_next,...,earbud_right_q,earbud_right_g,earbud_left_test,earbud_right_test,ecg_test,ppg_finger_test,ppg_ear_test,ppg_wrist_test,pcg_test,scg_test
98990,rp1,0,716,1446,0.000000,0.000000,770.0,1032.0,808.0,1385.0,...,793,1271,False,False,True,True,False,False,True,True
98991,rp1,1,1446,2163,0.000000,0.000000,1488.0,1756.0,1657.0,2177.0,...,1450,1969,False,False,True,True,False,False,True,True
98992,rp1,2,2163,2899,0.000000,-0.329590,2188.0,2329.0,2177.0,2379.0,...,2431,2848,False,False,True,False,False,False,True,True
98993,rp1,3,2899,3656,86.196899,35.623169,2922.0,3350.0,2924.0,3865.0,...,2848,3452,False,False,True,True,True,False,True,True
98994,rp1,4,3656,4441,86.196899,35.623169,3688.0,3937.0,3865.0,4329.0,...,3911,4381,False,False,True,True,False,True,True,True

### Quality check comparison

In [12]:
rp1_Wrist["quality_check_passed"].mean()

0.34961204929256046

In [18]:
rp1_fiducials["ppg_wrist_test"].mean()

0.34961204929256046